---   # rust-bitcoin CI: If you edit this file please update README.md
on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - 'test-ci/**'
  pull_request:

name: Continuous integration

jobs:
  Integration:
    name: Integration tests against pinheadmz/bitcoin:pr35182-ddefe4263b
    runs-on: ubuntu-latest
    env:
      BITCOIND_SKIP_DOWNLOAD: "1"
    strategy:
      fail-fast: false
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Select toolchain"
        uses: dtolnay/rust-toolchain@stable
      - name: "Pull bitcoind from docker image"
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          docker pull pinheadmz/bitcoin:pr35182-ddefe4263b
          cid=$(docker create pinheadmz/bitcoin:pr35182-ddefe4263b)
          docker cp $cid:/opt/bin/bitcoind   $GITHUB_WORKSPACE/bin/bitcoind
          docker cp $cid:/opt/bin/bitcoin-cli $GITHUB_WORKSPACE/bin/bitcoin-cli
          docker rm $cid
          chmod +x $GITHUB_WORKSPACE/bin/*
          sudo apt-get update -y
          sudo apt-get install -y libevent-dev libboost-dev libzmq3-dev libsqlite3-dev
          $GITHUB_WORKSPACE/bin/bitcoind -version
          echo "BITCOIND_EXE=$GITHUB_WORKSPACE/bin/bitcoind" >> $GITHUB_ENV
      - name: "Run integration tests"
        run: cd integration_test && cargo test --features=31_0
