---   # rust-bitcoin CI: If you edit this file please update README.md
on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - 'test-ci/**'
  pull_request:

name: Continuous integration

jobs:
  Integration:                  # 1 job for each bitcoind version we support.
    name: Integration tests - stable toolchain
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          [
            "31_0",
          ]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/setup-rbmt@6560b728ae6a81af9d92713b630ba26772fbd970 # v0.1.0
      - name: "Cache downloaded bitcoind"
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.cache/corepc/bitcoind
          key: bitcoind-${{ runner.os }}-${{ runner.arch }}-${{ matrix.version }}
      - name: "Run integration tests"
        env:
          BITCOIND_DOWNLOAD_DIR: ${{ github.workspace }}/.cache/corepc/bitcoind
        run: cd integration_test && cargo test --features=${{ matrix.version }},download
